// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxta_H6fvn3VCfM8Ad3RRDQhH8ZLUziM',
    appId: '1:538647707022:web:a10fb8613ce42ba443f8df',
    messagingSenderId: '538647707022',
    projectId: 'salman-1ce8f',
    authDomain: 'salman-1ce8f.firebaseapp.com',
    storageBucket: 'salman-1ce8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEPJmirllrI0rNjQ8UzLmQGxdHT2N7Z2Q',
    appId: '1:538647707022:android:44159bf4d817937543f8df',
    messagingSenderId: '538647707022',
    projectId: 'salman-1ce8f',
    storageBucket: 'salman-1ce8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB700jElw33hh6-wp_rxCx_gxgPcObqRtU',
    appId: '1:538647707022:ios:7666a27060de7c8843f8df',
    messagingSenderId: '538647707022',
    projectId: 'salman-1ce8f',
    storageBucket: 'salman-1ce8f.firebasestorage.app',
    iosBundleId: 'com.example.genzProtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB700jElw33hh6-wp_rxCx_gxgPcObqRtU',
    appId: '1:538647707022:ios:7666a27060de7c8843f8df',
    messagingSenderId: '538647707022',
    projectId: 'salman-1ce8f',
    storageBucket: 'salman-1ce8f.firebasestorage.app',
    iosBundleId: 'com.example.genzProtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxta_H6fvn3VCfM8Ad3RRDQhH8ZLUziM',
    appId: '1:538647707022:web:a9881877fbee1c1443f8df',
    messagingSenderId: '538647707022',
    projectId: 'salman-1ce8f',
    authDomain: 'salman-1ce8f.firebaseapp.com',
    storageBucket: 'salman-1ce8f.firebasestorage.app',
  );

}